/*
 * DTYPES.H
 * Copyright (C) 1989-1998 all rights reserved by Type Solutions, Inc. Plaistow, NH, USA.
 * Author: Sampo Kaasila
 *
 * This software is the property of Type Solutions, Inc. and it is furnished
 * under a license and may be used and copied only in accordance with the
 * terms of such license and with the inclusion of the above copyright notice.
 * This software or any other copies thereof may not be provided or otherwise
 * made available to any other person or entity except as allowed under license.
 * No title to and ownership of the software or intellectual property
 * therewithin is hereby transferred.
 *
 * This information in this software is subject to change without notice
 */
#ifndef __T2K_DTYPES__
#define __T2K_DTYPES__
#define int8 signed char
#define int16 short
#define int32 long

#define F26Dot6  long
#define F16Dot16 long

#define ONE16Dot16 0x10000


#ifndef false

#define false 0

#endif



#ifndef true

#define true 1

#endif

#endif /* _T2K_DTYPES__ */


